### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by xdevs23** [DerpFest-AOSP/vendor_support#4]
Would be great if you could add a license file to this repository, ideally one that is compatible with the Settings app (I think that should be Apache 2.0)

**Comment by NurKeinNeid** [comment]
Thank you! Its done: https://github.com/DerpFest-AOSP/vendor_support/commit/9d88317d9660bb03ac660671ac5290160e891a4c

**Comment by xdevs23** [comment]
Thanks!
